[ai]
enabled = true
inline_tooltip = false
mode = "agent"
rules = ""

[ai.custom_providers.jetstream]
api_key = "jetstream"
base_url = "https://llm.jetstream-cloud.org/v1"

[ai.models]
autocomplete_model = "jetstream/gpt-oss-120b"
chat_model = "jetstream/gpt-oss-120b"
custom_models = ["jetstream/gpt-oss-120b", "jetstream/Llama-4-Scout"]
displayed_models = ["jetstream/gpt-oss-120b", "jetstream/Llama-4-Scout"]

[completion]
activate_on_typing = true
copilot = "custom"
